### ISSUE TITLE
Switch from wifi to 3G cellular ... reload app

### ISSUE THREAD

**Issue by dartunder** [KulpLights/fpp-FPPMon#7]
Switching from wifi to 3G cellular requires closing the app and reloading on iPhone.  Otherwise, the app will not connect to the FPP device.

**Comment by dartunder** [comment]
The initial page shows the controller, but clicking on the controller is where the issue shows up.

You can test this by connecting via wifi opening the controller page; it loads ok. 
Then turning off wifi on the phone (I have an iPhone), and switching back to the app, the controller will list, but clicking it will hang.
Shut down the app, restart the app, and it works as expected.

**Comment by dkulp** [comment]
This is "somewhat" fixed with 1.1 now available in the app stores.   It can take up to about a minute for it to realize the network has changes and re-create the communications.   Just clicking back to the main device list and re-clicking on the device should now work without having to re-start the entire app.

**Comment by dartunder** [comment]
Confirmed as fixed.. Thanks.  I don't think having to move back to the selection page is a big deal. I would expect that.
